<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-3EO8411" ignored="0" name="Test" tests="34" failures="17" timestamp="2022-06-06T20:32:51 GMT+07:00" time="0.091" errors="0">
  <testcase name="test1" time="0.005" classname="online_tusur.unit_online_tusur.NewTest">
    <failure type="java.lang.AssertionError" message="expected [18] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [0]
at online_tusur.unit_online_tusur.NewTest.test1(NewTest.java:51)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.0" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.0" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest">
    <failure type="java.lang.AssertionError" message="expected [18] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at online_tusur.unit_online_tusur.NewTest.test5(NewTest.java:39)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test2" time="0.0" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test3" time="0.001" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test4" time="0.001" classname="online_tusur.unit_online_tusur.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at online_tusur.unit_online_tusur.NewTest.test4(NewTest.java:78)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test1" time="0.003" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test1" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test1" time="0.008" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;50&amp;gt; but was: &amp;lt;18&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <50> but was: <18>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test1(FactoryStydentTest.java:31)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;32&amp;gt; but was: &amp;lt;18&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <32> but was: <18>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test1(FactoryStydentTest.java:31)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test2" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;18&amp;gt; but was: &amp;lt;32&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <18> but was: <32>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test2(FactoryStydentTest.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;18&amp;gt; but was: &amp;lt;32&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <18> but was: <32>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test2(FactoryStydentTest.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;50&amp;gt; but was: &amp;lt;32&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <50> but was: <32>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test2(FactoryStydentTest.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test2" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;18&amp;gt; but was: &amp;lt;32&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <18> but was: <32>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test2(FactoryStydentTest.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;18&amp;gt; but was: &amp;lt;50&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <18> but was: <50>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test3(FactoryStydentTest.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;18&amp;gt; but was: &amp;lt;50&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <18> but was: <50>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test3(FactoryStydentTest.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test3" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;32&amp;gt; but was: &amp;lt;50&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <32> but was: <50>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test3(FactoryStydentTest.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;18&amp;gt; but was: &amp;lt;50&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <18> but was: <50>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
at online_tusur.unit_online_tusur.FactoryStydentTest.test3(FactoryStydentTest.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test4" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Ivaaaaan&amp;gt; but was: &amp;lt;Ivan&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Ivaaaaan> but was: <Ivan>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
at online_tusur.unit_online_tusur.FactoryStydentTest.test4(FactoryStydentTest.java:51)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test4" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test4" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Ivaaaaan&amp;gt; but was: &amp;lt;Ivan&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Ivaaaaan> but was: <Ivan>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
at online_tusur.unit_online_tusur.FactoryStydentTest.test4(FactoryStydentTest.java:51)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.0" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test5" time="0.0" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Radiiiionov&amp;gt; but was: &amp;lt;Radionov&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Radiiiionov> but was: <Radionov>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
at online_tusur.unit_online_tusur.FactoryStydentTest.test5(FactoryStydentTest.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Radiiiionov&amp;gt; but was: &amp;lt;Radionov&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Radiiiionov> but was: <Radionov>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
at online_tusur.unit_online_tusur.FactoryStydentTest.test5(FactoryStydentTest.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.FactoryStydentTest"/>
</testsuite> <!-- Test -->
